#!/usr/bin/env python3
"""Generate the Jev question reference from the production payload builders."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import jev
import jev_qualification as fixtures
from jev_contract import DEFAULT_JEV_POLICY
from jev_questions import ROUTING_QUESTION_VERSION, JUDGING_QUESTION_VERSION


def manifest():
    policy = fixtures.policy()
    packet = fixtures.route_fixture()
    packet["records"] = []  # Examples assert no real capability or outcome.
    routing = jev.route_payload(packet, jev.route_ranking(packet, policy), policy)
    judging = jev.judge_payload(fixtures.judge_fixture(), policy)
    return {
        "schema": "ultra-delegation-jev-questions-v1",
        "routing_version": ROUTING_QUESTION_VERSION,
        "judging_version": JUDGING_QUESTION_VERSION,
        "defaults": DEFAULT_JEV_POLICY,
        "routing": {"state_fields": sorted(routing["state"]),
                    "candidate_fields": sorted(routing["state"]["candidates"][0]),
                    "questions": routing["questions"], "question_hash": jev.hash_value(routing["questions"])},
        "judging": {"state_fields": sorted(judging["state"]),
                    "candidate_fields": sorted(judging["state"]["candidates"][0]),
                    "questions": judging["questions"], "question_hash": jev.hash_value(judging["questions"])},
    }


def render(data):
    p = data["defaults"]
    lines = ["# Jev question contract", "",
             "Generated by `scripts/jev_docs.py` from the production payload builders. Do not edit this file directly.", "",
             "Refresh: `python3 <skill>/scripts/jev_docs.py --write`. Check freshness: `python3 <skill>/scripts/jev_docs.py --check`.",
             "CI rejects drift. The adjacent JSON contains the machine-readable contract and question hashes.", "",
             "## Current request boundary", "",
             "The coordinator prepares the task, requirements, discovered profiles, and sanitized evidence. The adapter never reads conversation history or source files to construct state.",
             "Code first enforces context stops, coordinator-owned work, host/provider scope, exclusions, quarantine, evidence freshness, and eligible user choices/project pins. User choices and pins bypass Jev.",
             "Each eligible candidate receives its own suitability question. All questions see the same state in one request; they cannot consume one another's answers. Question IDs are response keys, not instructions seen by the model.", "",
             f"Default model: `{p['model']}`. Routing is `{p['routing']}` and judging is `{p['judging']}` until enabled independently. Sharing permissions are independent too.", "",
             "## Exact routing questions", "",
             f"Version: `{data['routing_version']}`. The example has two candidates; `fit_i` repeats for each candidate in deterministic ranking order.", "",
             f"State fields: {', '.join('`'+k+'`' for k in data['routing']['state_fields'])}.",
             f"Candidate fields: {', '.join('`'+k+'`' for k in data['routing']['candidate_fields'])}.", "",
             "```json", json.dumps(data["routing"]["questions"], indent=2), "```", "",
             "## How code consumes routing answers", "",
             f"The default suitability threshold is **{p['suitability_threshold']:.2f}**, an experimental operating point. `ambiguous` and `retain` must each be no greater than `1 - threshold`; a candidate's `fit_i` must be at least `threshold`.",
             "Code takes the first suitable established candidate in evidence-tier/cost order. Imported priors retain first-use verification. Unknown costs remain unknown. Suitable unproven candidates can only become controlled-experiment nominations under the existing one-variable rules.",
             "No suitable established candidate or permissible experiment means coordinator handling. More than 12 eligible candidates requires upstream shortlisting or coordinator comparison. Shadow mode retains an established baseline. Service failure returns unavailable and the original ranking.",
             "Before dispatch, `recheck` verifies the saved event, packet/policy hashes, age, current eligibility, and context guard. The host executes the worker.", "",
             "## Atomicity audit and proposed experiment", "",
             "The current questions are separate bounded judgments, but are not fully decomposed: `retain` groups several reasons to retain work, and `fit_i` combines task requirements and scope. This reference documents v1 exactly; it does not claim that decomposition or the threshold is validated.",
             "A future question-version experiment should separate unclear requirements, each independently actionable retention reason, candidate task match, and scope exceeding demonstrated capability. Keep evidence sufficiency and hard permissions in code. Batch independent questions, combine their signals deterministically, and compare against v1 on the same calibration/test split before adoption.",
             "Several candidates may all be suitable. Keep per-candidate yes/no judgments rather than forcing a single winner through Choice. Jev suitability is not observed worker success. Noul has no separate confidence field; Choice/Score confidence describes distribution concentration, not calibrated downstream correctness.", "",
             "## Exact shadow judging questions", "",
             f"Version: `{data['judging_version']}`; rubric: `{p['rubric_version']}`. Only candidate 0 is shown here; the JSON contract includes both examples.",
             f"State fields: {', '.join('`'+k+'`' for k in data['judging']['state_fields'])}.",
             f"Candidate fields: {', '.join('`'+k+'`' for k in data['judging']['candidate_fields'])}. Worker identity, cost, and reference judgments are omitted.", "",
             "```json", json.dumps({k: v for k, v in data["judging"]["questions"].items() if k.endswith("_0")}, indent=2), "```", "",
             "The current shadow suggestion averages four dimension scores after scaling 0–4 to 0–100, requires sufficient evidence, and requires observed mandatory gates to pass. A high average can compensate for low coverage; this is a known limitation of v1 shadow suggestions. These suggestions never establish acceptance or promotion.",
             "Downstream benchmark assessments use independent reviewer observations, per-dimension floors, critical-defect vetoes, and deterministic gates. They remain distinct from these Jev shadow scores.", "",
             "## Provenance and maintenance", "",
             "Changing question text changes `question_hash`. Changing questions requires a question-version bump and fresh captured responses before benchmarking. CI compares generated JSON/Markdown against the runtime builders; it checks synchronization, not semantic quality.",
             "Preview a specific real packet with `jev.py route --input packet.json --dry-run`. That validates and displays the actual outbound payload without looking up credentials or making a request. Keep payload previews local.",
             "See [benchmark workflow](jev-benchmark.md), [shortlists](shortlist.md), and [setup and permissions](jev.md).", "",
             "Primary references: [Noul](https://docs.typesafe.ai/primitives/noul), [confidence](https://docs.typesafe.ai/confidence), [batched questions](https://docs.typesafe.ai/patterns/fan-out).", ""]
    return "\n".join(lines)


def outputs():
    data = manifest()
    return {"jev-questions.json": json.dumps(data, indent=2, sort_keys=True) + "\n", "jev-questions.md": render(data)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1] / "references"
    stale = []
    for name, content in outputs().items():
        target = root / name
        if target.is_symlink():
            print("Refusing symlink generated reference", file=sys.stderr)
            return 1
        if args.write:
            target.write_text(content, encoding="utf-8", newline="\n")
        elif not target.exists() or target.read_text(encoding="utf-8") != content:
            stale.append(name)
    if stale:
        print("Stale generated Jev references: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("Jev question references " + ("updated" if args.write else "current"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
